#!/usr/bin/env python3
"""Static preflight scan for manuscript drafting residue.

This script scans text-like manuscript files for explicit AI residue,
placeholders, unresolved citations, Markdown/LaTeX artifacts, and common
submission-risk phrases.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Iterable, List, Tuple

SUPPORTED_EXTENSIONS = {".txt", ".md", ".tex", ".bib", ".ris"}
OPTIONAL_EXTENSIONS = {".docx", ".pdf"}

PATTERNS: List[Tuple[str, str, str]] = [
    ("BLOCKER", "explicit_ai_residue", r"\b(as an AI language model|ChatGPT|Claude|Gemini|generated by AI|AI-generated|prompt)\b"),
    ("BLOCKER", "avoid_ai_detection_residue", r"\b(avoid AI detection|humanize this|make it undetectable|bypass detector)\b"),
    ("MAJOR", "placeholder", r"(TODO|TBD|FIXME|\[insert citation\]|\[add reference\]|\[figure here\]|待补充|请核实|占位)"),
    ("MAJOR", "unresolved_latex", r"(\\cite\{|\\ref\{|\\label\{|\?\?)"),
    ("MAJOR", "markdown_artifact", r"(^```|^#{1,6}\s+|\|\s*---\s*\|)"),
    ("MAJOR", "editorial_instruction", r"\b(revise this|polish this|make this more scientific|expand this paragraph|needs citation)\b"),
    ("MINOR", "ai_style_risk", r"\b(delves? into|multifaceted|plays a pivotal role|it is important to note|underscore[s]?|crucial)\b"),
    ("MINOR", "overclaim_risk", r"\b(first|novel|unique|unprecedented|groundbreaking|paradigm-shifting)\b"),
]


def read_text(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix in SUPPORTED_EXTENSIONS:
        return path.read_text(encoding="utf-8", errors="replace")

    if suffix == ".docx":
        try:
            import docx  # type: ignore
        except Exception as exc:  # pragma: no cover
            raise RuntimeError("python-docx is required for .docx files") from exc
        doc = docx.Document(str(path))
        return "\n".join(p.text for p in doc.paragraphs)

    if suffix == ".pdf":
        try:
            import fitz  # type: ignore
        except Exception as exc:  # pragma: no cover
            raise RuntimeError("PyMuPDF is required for .pdf files") from exc
        parts = []
        with fitz.open(str(path)) as pdf:
            for page in pdf:
                parts.append(page.get_text())
        return "\n".join(parts)

    raise RuntimeError(f"Unsupported extension: {suffix}")


def iter_files(root: Path) -> Iterable[Path]:
    if root.is_file():
        yield root
        return
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS | OPTIONAL_EXTENSIONS:
            yield path


def scan_file(path: Path):
    try:
        text = read_text(path)
    except Exception as exc:
        yield {
            "severity": "MANUAL",
            "rule": "unreadable_file",
            "file": str(path),
            "line": "",
            "match": str(exc),
            "context": "",
        }
        return

    lines = text.splitlines()
    for i, line in enumerate(lines, start=1):
        for severity, rule, pattern in PATTERNS:
            if re.search(pattern, line, flags=re.IGNORECASE):
                yield {
                    "severity": severity,
                    "rule": rule,
                    "file": str(path),
                    "line": i,
                    "match": re.search(pattern, line, flags=re.IGNORECASE).group(0),
                    "context": line.strip()[:500],
                }


def main() -> int:
    parser = argparse.ArgumentParser(description="Static manuscript residue scan")
    parser.add_argument("target", help="Manuscript file or folder")
    parser.add_argument("--out", default="static_scan.tsv", help="Output TSV file")
    args = parser.parse_args()

    root = Path(args.target)
    rows = []
    for path in iter_files(root):
        rows.extend(scan_file(path))

    with open(args.out, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["severity", "rule", "file", "line", "match", "context"], delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote {len(rows)} findings to {args.out}")
    return 1 if any(r["severity"] == "BLOCKER" for r in rows) else 0


if __name__ == "__main__":
    sys.exit(main())
